import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/navbar/Navbar";
import Footer from "@/components/shared/footer/Footer";
import Script from "next/script";
import Head from "next/head";
import { Montserrat } from "next/font/google";

import dynamic from "next/dynamic";

const NextProgress = dynamic(() => import("@/components/shared/Loader"), {
  ssr: false,
});

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ibtidaa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={montserrat.className}>
        <Navbar />
        <NextProgress />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
